// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievements.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAchievementByID = `-- name: GetAchievementByID :one
SELECT id, name_key, description_key, icon, target, category, created_at FROM achievements WHERE id = $1
`

func (q *Queries) GetAchievementByID(ctx context.Context, id pgtype.UUID) (Achievement, error) {
	row := q.db.QueryRow(ctx, getAchievementByID, id)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.NameKey,
		&i.DescriptionKey,
		&i.Icon,
		&i.Target,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getAchievementsByCategory = `-- name: GetAchievementsByCategory :many
SELECT id, name_key, description_key, icon, target, category, created_at FROM achievements WHERE category = $1 ORDER BY target
`

func (q *Queries) GetAchievementsByCategory(ctx context.Context, category string) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievementsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.NameKey,
			&i.DescriptionKey,
			&i.Icon,
			&i.Target,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAchievements = `-- name: GetAllAchievements :many
SELECT id, name_key, description_key, icon, target, category, created_at FROM achievements ORDER BY category, target
`

func (q *Queries) GetAllAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAllAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.NameKey,
			&i.DescriptionKey,
			&i.Icon,
			&i.Target,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAchievement = `-- name: GetUserAchievement :one
SELECT id, user_id, achievement_id, unlocked, progress, unlocked_at, created_at, updated_at FROM user_achievements
WHERE user_id = $1 AND achievement_id = $2
`

type GetUserAchievementParams struct {
	UserID        pgtype.UUID
	AchievementID pgtype.UUID
}

func (q *Queries) GetUserAchievement(ctx context.Context, arg GetUserAchievementParams) (UserAchievement, error) {
	row := q.db.QueryRow(ctx, getUserAchievement, arg.UserID, arg.AchievementID)
	var i UserAchievement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AchievementID,
		&i.Unlocked,
		&i.Progress,
		&i.UnlockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAchievements = `-- name: GetUserAchievements :many
SELECT ua.id, ua.user_id, ua.achievement_id, ua.unlocked, ua.progress, ua.unlocked_at, ua.created_at, ua.updated_at, a.name_key, a.description_key, a.icon, a.target, a.category
FROM user_achievements ua
JOIN achievements a ON ua.achievement_id = a.id
WHERE ua.user_id = $1
ORDER BY ua.unlocked DESC, a.category, a.target
`

type GetUserAchievementsRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	AchievementID  pgtype.UUID
	Unlocked       bool
	Progress       int
	UnlockedAt     *time.Time
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
	NameKey        string
	DescriptionKey string
	Icon           string
	Target         int
	Category       string
}

func (q *Queries) GetUserAchievements(ctx context.Context, userID pgtype.UUID) ([]GetUserAchievementsRow, error) {
	rows, err := q.db.Query(ctx, getUserAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAchievementsRow{}
	for rows.Next() {
		var i GetUserAchievementsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AchievementID,
			&i.Unlocked,
			&i.Progress,
			&i.UnlockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NameKey,
			&i.DescriptionKey,
			&i.Icon,
			&i.Target,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnlockedAchievements = `-- name: GetUserUnlockedAchievements :many
SELECT ua.id, ua.user_id, ua.achievement_id, ua.unlocked, ua.progress, ua.unlocked_at, ua.created_at, ua.updated_at, a.name_key, a.description_key, a.icon, a.target, a.category
FROM user_achievements ua
JOIN achievements a ON ua.achievement_id = a.id
WHERE ua.user_id = $1 AND ua.unlocked = true
ORDER BY ua.unlocked_at DESC
`

type GetUserUnlockedAchievementsRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	AchievementID  pgtype.UUID
	Unlocked       bool
	Progress       int
	UnlockedAt     *time.Time
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
	NameKey        string
	DescriptionKey string
	Icon           string
	Target         int
	Category       string
}

func (q *Queries) GetUserUnlockedAchievements(ctx context.Context, userID pgtype.UUID) ([]GetUserUnlockedAchievementsRow, error) {
	rows, err := q.db.Query(ctx, getUserUnlockedAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserUnlockedAchievementsRow{}
	for rows.Next() {
		var i GetUserUnlockedAchievementsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AchievementID,
			&i.Unlocked,
			&i.Progress,
			&i.UnlockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NameKey,
			&i.DescriptionKey,
			&i.Icon,
			&i.Target,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAchievementProgress = `-- name: UpdateAchievementProgress :exec
UPDATE user_achievements SET
    progress = $3,
    updated_at = NOW()
WHERE user_id = $1 AND achievement_id = $2
`

type UpdateAchievementProgressParams struct {
	UserID        pgtype.UUID
	AchievementID pgtype.UUID
	Progress      int
}

func (q *Queries) UpdateAchievementProgress(ctx context.Context, arg UpdateAchievementProgressParams) error {
	_, err := q.db.Exec(ctx, updateAchievementProgress, arg.UserID, arg.AchievementID, arg.Progress)
	return err
}

const upsertUserAchievement = `-- name: UpsertUserAchievement :exec
INSERT INTO user_achievements (user_id, achievement_id, unlocked, progress, unlocked_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, achievement_id) DO UPDATE SET
    unlocked = EXCLUDED.unlocked,
    progress = EXCLUDED.progress,
    unlocked_at = EXCLUDED.unlocked_at,
    updated_at = NOW()
`

type UpsertUserAchievementParams struct {
	UserID        pgtype.UUID
	AchievementID pgtype.UUID
	Unlocked      bool
	Progress      int
	UnlockedAt    *time.Time
}

func (q *Queries) UpsertUserAchievement(ctx context.Context, arg UpsertUserAchievementParams) error {
	_, err := q.db.Exec(ctx, upsertUserAchievement,
		arg.UserID,
		arg.AchievementID,
		arg.Unlocked,
		arg.Progress,
		arg.UnlockedAt,
	)
	return err
}
