// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrResetAIUsage = `-- name: CreateOrResetAIUsage :one
INSERT INTO ai_usage (
    user_id,
    feature,
    usage_count,
    quota,
    period_start,
    period_end
) VALUES (
    $1, $2, 0, $3, $4, $5
)
ON CONFLICT (user_id, feature, period_start) DO UPDATE SET
    usage_count = 0,
    quota = EXCLUDED.quota,
    updated_at = NOW()
RETURNING id, user_id, feature, usage_count, quota, period_start, period_end, created_at, updated_at
`

type CreateOrResetAIUsageParams struct {
	UserID      uuid.UUID
	Feature     string
	Quota       int
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

func (q *Queries) CreateOrResetAIUsage(ctx context.Context, arg CreateOrResetAIUsageParams) (AiUsage, error) {
	row := q.db.QueryRow(ctx, createOrResetAIUsage,
		arg.UserID,
		arg.Feature,
		arg.Quota,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i AiUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Feature,
		&i.UsageCount,
		&i.Quota,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIUsage = `-- name: GetAIUsage :one
SELECT id, user_id, feature, usage_count, quota, period_start, period_end, created_at, updated_at FROM ai_usage
WHERE user_id = $1
AND feature = $2
AND period_end > NOW()
ORDER BY period_start DESC
LIMIT 1
`

type GetAIUsageParams struct {
	UserID  uuid.UUID
	Feature string
}

func (q *Queries) GetAIUsage(ctx context.Context, arg GetAIUsageParams) (AiUsage, error) {
	row := q.db.QueryRow(ctx, getAIUsage, arg.UserID, arg.Feature)
	var i AiUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Feature,
		&i.UsageCount,
		&i.Quota,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIUsageByPeriod = `-- name: GetAIUsageByPeriod :one
SELECT id, user_id, feature, usage_count, quota, period_start, period_end, created_at, updated_at FROM ai_usage
WHERE user_id = $1
AND feature = $2
AND period_start = $3
LIMIT 1
`

type GetAIUsageByPeriodParams struct {
	UserID      uuid.UUID
	Feature     string
	PeriodStart pgtype.Timestamptz
}

func (q *Queries) GetAIUsageByPeriod(ctx context.Context, arg GetAIUsageByPeriodParams) (AiUsage, error) {
	row := q.db.QueryRow(ctx, getAIUsageByPeriod, arg.UserID, arg.Feature, arg.PeriodStart)
	var i AiUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Feature,
		&i.UsageCount,
		&i.Quota,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAIUsage = `-- name: IncrementAIUsage :one
INSERT INTO ai_usage (
    user_id,
    feature,
    usage_count,
    quota,
    period_start,
    period_end
) VALUES (
    $1, $2, 1, $3, $4, $5
)
ON CONFLICT (user_id, feature, period_start) DO UPDATE SET
    usage_count = ai_usage.usage_count + 1,
    updated_at = NOW()
RETURNING id, user_id, feature, usage_count, quota, period_start, period_end, created_at, updated_at
`

type IncrementAIUsageParams struct {
	UserID      uuid.UUID
	Feature     string
	Quota       int
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

func (q *Queries) IncrementAIUsage(ctx context.Context, arg IncrementAIUsageParams) (AiUsage, error) {
	row := q.db.QueryRow(ctx, incrementAIUsage,
		arg.UserID,
		arg.Feature,
		arg.Quota,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i AiUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Feature,
		&i.UsageCount,
		&i.Quota,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAIUsage = `-- name: ListUserAIUsage :many
SELECT id, user_id, feature, usage_count, quota, period_start, period_end, created_at, updated_at FROM ai_usage
WHERE user_id = $1
AND period_end > NOW()
ORDER BY feature ASC
`

func (q *Queries) ListUserAIUsage(ctx context.Context, userID uuid.UUID) ([]AiUsage, error) {
	rows, err := q.db.Query(ctx, listUserAIUsage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiUsage{}
	for rows.Next() {
		var i AiUsage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Feature,
			&i.UsageCount,
			&i.Quota,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAIUsage = `-- name: ResetAIUsage :exec
DELETE FROM ai_usage
WHERE period_end < NOW()
`

func (q *Queries) ResetAIUsage(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAIUsage)
	return err
}
