// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (
    user_id, type, title, description, user_email,
    platform, os_version, app_version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, type, title, description, user_email, platform, os_version, app_version, status, created_at
`

type CreateFeedbackParams struct {
	UserID      uuid.UUID
	Type        string
	Title       string
	Description string
	UserEmail   string
	Platform    *string
	OsVersion   *string
	AppVersion  *string
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.UserEmail,
		arg.Platform,
		arg.OsVersion,
		arg.AppVersion,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.UserEmail,
		&i.Platform,
		&i.OsVersion,
		&i.AppVersion,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedback = `-- name: GetFeedback :one
SELECT id, user_id, type, title, description, user_email, platform, os_version, app_version, status, created_at FROM feedback WHERE id = $1
`

func (q *Queries) GetFeedback(ctx context.Context, id uuid.UUID) (Feedback, error) {
	row := q.db.QueryRow(ctx, getFeedback, id)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.UserEmail,
		&i.Platform,
		&i.OsVersion,
		&i.AppVersion,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedbackByType = `-- name: GetFeedbackByType :many
SELECT id, user_id, type, title, description, user_email, platform, os_version, app_version, status, created_at FROM feedback
WHERE type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetFeedbackByTypeParams struct {
	Type   string
	Limit  int
	Offset int
}

func (q *Queries) GetFeedbackByType(ctx context.Context, arg GetFeedbackByTypeParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, getFeedbackByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.UserEmail,
			&i.Platform,
			&i.OsVersion,
			&i.AppVersion,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackByUser = `-- name: GetFeedbackByUser :many
SELECT id, user_id, type, title, description, user_email, platform, os_version, app_version, status, created_at FROM feedback
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFeedbackByUser(ctx context.Context, userID uuid.UUID) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, getFeedbackByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.UserEmail,
			&i.Platform,
			&i.OsVersion,
			&i.AppVersion,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedback = `-- name: ListFeedback :many
SELECT id, user_id, type, title, description, user_email, platform, os_version, app_version, status, created_at FROM feedback
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFeedbackParams struct {
	Limit  int
	Offset int
}

func (q *Queries) ListFeedback(ctx context.Context, arg ListFeedbackParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listFeedback, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.UserEmail,
			&i.Platform,
			&i.OsVersion,
			&i.AppVersion,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedbackStatus = `-- name: UpdateFeedbackStatus :exec
UPDATE feedback SET status = $2 WHERE id = $1
`

type UpdateFeedbackStatusParams struct {
	ID     uuid.UUID
	Status *string
}

func (q *Queries) UpdateFeedbackStatus(ctx context.Context, arg UpdateFeedbackStatusParams) error {
	_, err := q.db.Exec(ctx, updateFeedbackStatus, arg.ID, arg.Status)
	return err
}
