// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_database.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFoodFromBarcode = `-- name: CreateFoodFromBarcode :one
INSERT INTO food_database (
    barcode, name, brand, calories, protein, carbs, fat,
    serving_size, serving_unit, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, brand, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, source, created_at, barcode, calories, protein, carbs, fat, serving_size, serving_unit, verified, updated_at, external_id
`

type CreateFoodFromBarcodeParams struct {
	Barcode     *string
	Name        string
	Brand       *string
	Calories    *int
	Protein     *float64
	Carbs       *float64
	Fat         *float64
	ServingSize *int
	ServingUnit *string
	Source      *string
}

func (q *Queries) CreateFoodFromBarcode(ctx context.Context, arg CreateFoodFromBarcodeParams) (FoodDatabase, error) {
	row := q.db.QueryRow(ctx, createFoodFromBarcode,
		arg.Barcode,
		arg.Name,
		arg.Brand,
		arg.Calories,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.ServingSize,
		arg.ServingUnit,
		arg.Source,
	)
	var i FoodDatabase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.CaloriesPer100g,
		&i.ProteinPer100g,
		&i.CarbsPer100g,
		&i.FatPer100g,
		&i.Source,
		&i.CreatedAt,
		&i.Barcode,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.ServingSize,
		&i.ServingUnit,
		&i.Verified,
		&i.UpdatedAt,
		&i.ExternalID,
	)
	return i, err
}

const getFoodByBarcode = `-- name: GetFoodByBarcode :one
SELECT id, name, brand, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, source, created_at, barcode, calories, protein, carbs, fat, serving_size, serving_unit, verified, updated_at, external_id FROM food_database WHERE barcode = $1
`

func (q *Queries) GetFoodByBarcode(ctx context.Context, barcode *string) (FoodDatabase, error) {
	row := q.db.QueryRow(ctx, getFoodByBarcode, barcode)
	var i FoodDatabase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.CaloriesPer100g,
		&i.ProteinPer100g,
		&i.CarbsPer100g,
		&i.FatPer100g,
		&i.Source,
		&i.CreatedAt,
		&i.Barcode,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.ServingSize,
		&i.ServingUnit,
		&i.Verified,
		&i.UpdatedAt,
		&i.ExternalID,
	)
	return i, err
}

const getFoodByID = `-- name: GetFoodByID :one
SELECT id, name, brand, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, source, created_at, barcode, calories, protein, carbs, fat, serving_size, serving_unit, verified, updated_at, external_id FROM food_database WHERE id = $1
`

func (q *Queries) GetFoodByID(ctx context.Context, id uuid.UUID) (FoodDatabase, error) {
	row := q.db.QueryRow(ctx, getFoodByID, id)
	var i FoodDatabase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.CaloriesPer100g,
		&i.ProteinPer100g,
		&i.CarbsPer100g,
		&i.FatPer100g,
		&i.Source,
		&i.CreatedAt,
		&i.Barcode,
		&i.Calories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.ServingSize,
		&i.ServingUnit,
		&i.Verified,
		&i.UpdatedAt,
		&i.ExternalID,
	)
	return i, err
}

const listVerifiedFoods = `-- name: ListVerifiedFoods :many
SELECT id, name, brand, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, source, created_at, barcode, calories, protein, carbs, fat, serving_size, serving_unit, verified, updated_at, external_id FROM food_database
WHERE verified = true
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListVerifiedFoodsParams struct {
	Limit  int
	Offset int
}

func (q *Queries) ListVerifiedFoods(ctx context.Context, arg ListVerifiedFoodsParams) ([]FoodDatabase, error) {
	rows, err := q.db.Query(ctx, listVerifiedFoods, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodDatabase{}
	for rows.Next() {
		var i FoodDatabase
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.CaloriesPer100g,
			&i.ProteinPer100g,
			&i.CarbsPer100g,
			&i.FatPer100g,
			&i.Source,
			&i.CreatedAt,
			&i.Barcode,
			&i.Calories,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.ServingSize,
			&i.ServingUnit,
			&i.Verified,
			&i.UpdatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFoodByName = `-- name: SearchFoodByName :many
SELECT id, name, brand, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, source, created_at, barcode, calories, protein, carbs, fat, serving_size, serving_unit, verified, updated_at, external_id FROM food_database
WHERE LOWER(name) LIKE LOWER($1)
ORDER BY verified DESC, name
LIMIT $2
`

type SearchFoodByNameParams struct {
	Lower string
	Limit int
}

func (q *Queries) SearchFoodByName(ctx context.Context, arg SearchFoodByNameParams) ([]FoodDatabase, error) {
	rows, err := q.db.Query(ctx, searchFoodByName, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodDatabase{}
	for rows.Next() {
		var i FoodDatabase
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.CaloriesPer100g,
			&i.ProteinPer100g,
			&i.CarbsPer100g,
			&i.FatPer100g,
			&i.Source,
			&i.CreatedAt,
			&i.Barcode,
			&i.Calories,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.ServingSize,
			&i.ServingUnit,
			&i.Verified,
			&i.UpdatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFoodVerified = `-- name: UpdateFoodVerified :exec
UPDATE food_database SET verified = $2, updated_at = NOW() WHERE id = $1
`

type UpdateFoodVerifiedParams struct {
	ID       uuid.UUID
	Verified *bool
}

func (q *Queries) UpdateFoodVerified(ctx context.Context, arg UpdateFoodVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateFoodVerified, arg.ID, arg.Verified)
	return err
}
