// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_items.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodItem = `-- name: CreateFoodItem :exec
INSERT INTO food_items (id, meal_id, name, portion_size, portion_unit, calories, protein_g, carbs_g, fat_g, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateFoodItemParams struct {
	ID          pgtype.UUID
	MealID      pgtype.UUID
	Name        string
	PortionSize pgtype.Numeric
	PortionUnit *string
	Calories    int
	ProteinG    pgtype.Numeric
	CarbsG      pgtype.Numeric
	FatG        pgtype.Numeric
	Source      *string
}

func (q *Queries) CreateFoodItem(ctx context.Context, arg CreateFoodItemParams) error {
	_, err := q.db.Exec(ctx, createFoodItem,
		arg.ID,
		arg.MealID,
		arg.Name,
		arg.PortionSize,
		arg.PortionUnit,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.Source,
	)
	return err
}

const createStandaloneFoodItem = `-- name: CreateStandaloneFoodItem :one
INSERT INTO food_items (id, meal_id, name, portion_size, portion_unit, calories, protein_g, carbs_g, fat_g, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, meal_id, name, portion_size, portion_unit, calories, protein_g, carbs_g, fat_g, source
`

type CreateStandaloneFoodItemParams struct {
	ID          pgtype.UUID
	MealID      pgtype.UUID
	Name        string
	PortionSize pgtype.Numeric
	PortionUnit *string
	Calories    int
	ProteinG    pgtype.Numeric
	CarbsG      pgtype.Numeric
	FatG        pgtype.Numeric
	Source      *string
}

func (q *Queries) CreateStandaloneFoodItem(ctx context.Context, arg CreateStandaloneFoodItemParams) (FoodItem, error) {
	row := q.db.QueryRow(ctx, createStandaloneFoodItem,
		arg.ID,
		arg.MealID,
		arg.Name,
		arg.PortionSize,
		arg.PortionUnit,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.Source,
	)
	var i FoodItem
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.Name,
		&i.PortionSize,
		&i.PortionUnit,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.Source,
	)
	return i, err
}

const deleteFoodItem = `-- name: DeleteFoodItem :exec
DELETE FROM food_items
WHERE id = $1
`

func (q *Queries) DeleteFoodItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFoodItem, id)
	return err
}

const getFoodItemByID = `-- name: GetFoodItemByID :one
SELECT id, meal_id, name, portion_size, portion_unit, calories, protein_g, carbs_g, fat_g, source
FROM food_items
WHERE id = $1
`

func (q *Queries) GetFoodItemByID(ctx context.Context, id pgtype.UUID) (FoodItem, error) {
	row := q.db.QueryRow(ctx, getFoodItemByID, id)
	var i FoodItem
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.Name,
		&i.PortionSize,
		&i.PortionUnit,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.Source,
	)
	return i, err
}

const getFoodItemsByMealID = `-- name: GetFoodItemsByMealID :many
SELECT id, meal_id, name, portion_size, portion_unit, calories, protein_g, carbs_g, fat_g, source
FROM food_items
WHERE meal_id = $1
`

func (q *Queries) GetFoodItemsByMealID(ctx context.Context, mealID pgtype.UUID) ([]FoodItem, error) {
	rows, err := q.db.Query(ctx, getFoodItemsByMealID, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodItem{}
	for rows.Next() {
		var i FoodItem
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.Name,
			&i.PortionSize,
			&i.PortionUnit,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodItemsByMealIDs = `-- name: GetFoodItemsByMealIDs :many
SELECT id, meal_id, name, portion_size, portion_unit, calories, protein_g, carbs_g, fat_g, source
FROM food_items
WHERE meal_id = ANY($1::uuid[])
`

func (q *Queries) GetFoodItemsByMealIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]FoodItem, error) {
	rows, err := q.db.Query(ctx, getFoodItemsByMealIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodItem{}
	for rows.Next() {
		var i FoodItem
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.Name,
			&i.PortionSize,
			&i.PortionUnit,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentFoods = `-- name: GetRecentFoods :many
SELECT DISTINCT ON (fi.name) 
    fi.name,
    fi.portion_size,
    fi.portion_unit,
    fi.calories,
    fi.protein_g,
    fi.carbs_g,
    fi.fat_g,
    m.created_at as last_used
FROM food_items fi
JOIN meals m ON fi.meal_id = m.id
WHERE m.user_id = $1
ORDER BY fi.name, m.created_at DESC
LIMIT $2
`

type GetRecentFoodsParams struct {
	UserID pgtype.UUID
	Limit  int
}

type GetRecentFoodsRow struct {
	Name        string
	PortionSize pgtype.Numeric
	PortionUnit *string
	Calories    int
	ProteinG    pgtype.Numeric
	CarbsG      pgtype.Numeric
	FatG        pgtype.Numeric
	LastUsed    *time.Time
}

func (q *Queries) GetRecentFoods(ctx context.Context, arg GetRecentFoodsParams) ([]GetRecentFoodsRow, error) {
	rows, err := q.db.Query(ctx, getRecentFoods, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentFoodsRow{}
	for rows.Next() {
		var i GetRecentFoodsRow
		if err := rows.Scan(
			&i.Name,
			&i.PortionSize,
			&i.PortionUnit,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFoodDatabase = `-- name: SearchFoodDatabase :many
SELECT id, name, brand, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, source, created_at
FROM food_database
WHERE to_tsvector('portuguese', name) @@ plainto_tsquery('portuguese', $1)
   OR name ILIKE '%' || $2 || '%'
ORDER BY ts_rank(to_tsvector('portuguese', name), plainto_tsquery('portuguese', $1)) DESC
LIMIT $3
`

type SearchFoodDatabaseParams struct {
	PlaintoTsquery string
	Column2        *string
	Limit          int
}

type SearchFoodDatabaseRow struct {
	ID              pgtype.UUID
	Name            string
	Brand           *string
	CaloriesPer100g *int
	ProteinPer100g  pgtype.Numeric
	CarbsPer100g    pgtype.Numeric
	FatPer100g      pgtype.Numeric
	Source          *string
	CreatedAt       *time.Time
}

func (q *Queries) SearchFoodDatabase(ctx context.Context, arg SearchFoodDatabaseParams) ([]SearchFoodDatabaseRow, error) {
	rows, err := q.db.Query(ctx, searchFoodDatabase, arg.PlaintoTsquery, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFoodDatabaseRow{}
	for rows.Next() {
		var i SearchFoodDatabaseRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.CaloriesPer100g,
			&i.ProteinPer100g,
			&i.CarbsPer100g,
			&i.FatPer100g,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFoodItem = `-- name: UpdateFoodItem :exec
UPDATE food_items
SET name = $2,
    portion_size = $3,
    portion_unit = $4,
    calories = $5,
    protein_g = $6,
    carbs_g = $7,
    fat_g = $8
WHERE id = $1
`

type UpdateFoodItemParams struct {
	ID          pgtype.UUID
	Name        string
	PortionSize pgtype.Numeric
	PortionUnit *string
	Calories    int
	ProteinG    pgtype.Numeric
	CarbsG      pgtype.Numeric
	FatG        pgtype.Numeric
}

func (q *Queries) UpdateFoodItem(ctx context.Context, arg UpdateFoodItemParams) error {
	_, err := q.db.Exec(ctx, updateFoodItem,
		arg.ID,
		arg.Name,
		arg.PortionSize,
		arg.PortionUnit,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
	)
	return err
}

const updateFoodItemComplete = `-- name: UpdateFoodItemComplete :one
UPDATE food_items
SET name = $2,
    portion_size = $3,
    portion_unit = $4,
    calories = $5,
    protein_g = $6,
    carbs_g = $7,
    fat_g = $8,
    source = $9
WHERE id = $1
RETURNING id, meal_id, name, portion_size, portion_unit, calories, protein_g, carbs_g, fat_g, source
`

type UpdateFoodItemCompleteParams struct {
	ID          pgtype.UUID
	Name        string
	PortionSize pgtype.Numeric
	PortionUnit *string
	Calories    int
	ProteinG    pgtype.Numeric
	CarbsG      pgtype.Numeric
	FatG        pgtype.Numeric
	Source      *string
}

func (q *Queries) UpdateFoodItemComplete(ctx context.Context, arg UpdateFoodItemCompleteParams) (FoodItem, error) {
	row := q.db.QueryRow(ctx, updateFoodItemComplete,
		arg.ID,
		arg.Name,
		arg.PortionSize,
		arg.PortionUnit,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.Source,
	)
	var i FoodItem
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.Name,
		&i.PortionSize,
		&i.PortionUnit,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.Source,
	)
	return i, err
}
