// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserGoalByUserID = `-- name: GetUserGoalByUserID :one
SELECT user_id, daily_calories, protein, carbs, fat, updated_at
FROM user_goals
WHERE user_id = $1
`

func (q *Queries) GetUserGoalByUserID(ctx context.Context, userID uuid.UUID) (UserGoal, error) {
	row := q.db.QueryRow(ctx, getUserGoalByUserID, userID)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.DailyCalories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserGoal = `-- name: UpsertUserGoal :one
INSERT INTO user_goals (user_id, daily_calories, protein, carbs, fat)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id)
DO UPDATE SET
    daily_calories = EXCLUDED.daily_calories,
    protein = EXCLUDED.protein,
    carbs = EXCLUDED.carbs,
    fat = EXCLUDED.fat,
    updated_at = NOW()
RETURNING user_id, daily_calories, protein, carbs, fat, updated_at
`

type UpsertUserGoalParams struct {
	UserID        uuid.UUID
	DailyCalories int
	Protein       *int
	Carbs         *int
	Fat           *int
}

func (q *Queries) UpsertUserGoal(ctx context.Context, arg UpsertUserGoalParams) (UserGoal, error) {
	row := q.db.QueryRow(ctx, upsertUserGoal,
		arg.UserID,
		arg.DailyCalories,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
	)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.DailyCalories,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.UpdatedAt,
	)
	return i, err
}
