// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserGoalByUserID = `-- name: GetUserGoalByUserID :one
SELECT user_id, daily_calories, protein_g, carbs_g, fat_g, updated_at
FROM user_goals
WHERE user_id = $1
`

func (q *Queries) GetUserGoalByUserID(ctx context.Context, userID pgtype.UUID) (UserGoal, error) {
	row := q.db.QueryRow(ctx, getUserGoalByUserID, userID)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.DailyCalories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserGoal = `-- name: UpsertUserGoal :one
INSERT INTO user_goals (user_id, daily_calories, protein_g, carbs_g, fat_g)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id)
DO UPDATE SET
    daily_calories = EXCLUDED.daily_calories,
    protein_g = EXCLUDED.protein_g,
    carbs_g = EXCLUDED.carbs_g,
    fat_g = EXCLUDED.fat_g,
    updated_at = NOW()
RETURNING user_id, daily_calories, protein_g, carbs_g, fat_g, updated_at
`

type UpsertUserGoalParams struct {
	UserID        pgtype.UUID
	DailyCalories int
	ProteinG      *int
	CarbsG        *int
	FatG          *int
}

func (q *Queries) UpsertUserGoal(ctx context.Context, arg UpsertUserGoalParams) (UserGoal, error) {
	row := q.db.QueryRow(ctx, upsertUserGoal,
		arg.UserID,
		arg.DailyCalories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
	)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.DailyCalories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.UpdatedAt,
	)
	return i, err
}
