// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (id, user_id, meal_type, meal_date, meal_time, photo_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, meal_type, meal_date, meal_time, photo_url, created_at
`

type CreateMealParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	MealType *string
	MealDate pgtype.Date
	MealTime pgtype.Time
	PhotoUrl *string
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.ID,
		arg.UserID,
		arg.MealType,
		arg.MealDate,
		arg.MealTime,
		arg.PhotoUrl,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealType,
		&i.MealDate,
		&i.MealTime,
		&i.PhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getMealByID = `-- name: GetMealByID :one
SELECT id, user_id, meal_type, meal_date, meal_time, photo_url, created_at
FROM meals
WHERE id = $1
`

func (q *Queries) GetMealByID(ctx context.Context, id pgtype.UUID) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealByID, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealType,
		&i.MealDate,
		&i.MealTime,
		&i.PhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getMealsByUserAndDate = `-- name: GetMealsByUserAndDate :many
SELECT id, user_id, meal_type, meal_date, meal_time, photo_url, created_at
FROM meals
WHERE user_id = $1 AND meal_date = $2
ORDER BY meal_time ASC, created_at ASC
`

type GetMealsByUserAndDateParams struct {
	UserID   pgtype.UUID
	MealDate pgtype.Date
}

func (q *Queries) GetMealsByUserAndDate(ctx context.Context, arg GetMealsByUserAndDateParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getMealsByUserAndDate, arg.UserID, arg.MealDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MealType,
			&i.MealDate,
			&i.MealTime,
			&i.PhotoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
