// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID             pgtype.UUID
	NameKey        string
	DescriptionKey string
	Icon           string
	Target         int
	Category       string
	CreatedAt      *time.Time
}

type AiUsage struct {
	ID          int64
	UserID      pgtype.UUID
	Feature     string
	UsageCount  int
	Quota       int
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Feedback struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Type        string
	Title       string
	Description string
	UserEmail   string
	Platform    *string
	OsVersion   *string
	AppVersion  *string
	Status      *string
	CreatedAt   *time.Time
}

type FoodDatabase struct {
	ID              pgtype.UUID
	Name            string
	Brand           *string
	CaloriesPer100g *int
	ProteinPer100g  pgtype.Numeric
	CarbsPer100g    pgtype.Numeric
	FatPer100g      pgtype.Numeric
	Source          *string
	CreatedAt       *time.Time
	Barcode         *string
	Calories        *int
	ProteinG        pgtype.Numeric
	CarbsG          pgtype.Numeric
	FatG            pgtype.Numeric
	ServingSize     *int
	ServingUnit     *string
	Verified        *bool
	UpdatedAt       *time.Time
}

type FoodItem struct {
	ID          pgtype.UUID
	MealID      pgtype.UUID
	Name        string
	PortionSize pgtype.Numeric
	PortionUnit *string
	Calories    int
	ProteinG    pgtype.Numeric
	CarbsG      pgtype.Numeric
	FatG        pgtype.Numeric
	Source      *string
}

type Meal struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	MealType  *string
	MealDate  pgtype.Date
	MealTime  pgtype.Time
	PhotoUrl  *string
	CreatedAt *time.Time
}

type Subscription struct {
	ID                              int64
	UserID                          pgtype.UUID
	RevenuecatUserID                string
	RevenuecatOriginalTransactionID *string
	IsActive                        bool
	Plan                            string
	IsTrial                         bool
	CurrentPeriodStart              pgtype.Timestamptz
	CurrentPeriodEnd                pgtype.Timestamptz
	LastEventID                     *string
	LastEventType                   *string
	LastEventAt                     pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

type User struct {
	ID                   pgtype.UUID
	FirebaseUid          string
	Email                *string
	DisplayName          *string
	PhotoUrl             *string
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
	Weight               *int
	Height               *int
	Age                  *int
	Gender               *string
	ActivityLevel        *string
	Language             *string
	NotificationsEnabled *bool
	Timezone             *string
}

type UserAchievement struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	AchievementID pgtype.UUID
	Unlocked      bool
	Progress      int
	UnlockedAt    *time.Time
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
}

type UserGoal struct {
	UserID        pgtype.UUID
	DailyCalories int
	ProteinG      *int
	CarbsG        *int
	FatG          *int
	UpdatedAt     *time.Time
}

type UserStat struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	CurrentStreak         int
	LongestStreak         int
	TotalMealsLogged      int
	TotalDaysLogged       int
	TotalCaloriesConsumed int
	TotalProteinConsumed  int
	TotalCarbsConsumed    int
	TotalFatConsumed      int
	LastLogDate           pgtype.Date
	CreatedAt             *time.Time
	UpdatedAt             *time.Time
}
