// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID             uuid.UUID
	NameKey        string
	DescriptionKey string
	Icon           string
	Target         int
	Category       string
	CreatedAt      *time.Time
}

type AiUsage struct {
	ID          int64
	UserID      uuid.UUID
	Feature     string
	UsageCount  int
	Quota       int
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Feedback struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Title       string
	Description string
	UserEmail   string
	Platform    *string
	OsVersion   *string
	AppVersion  *string
	Status      *string
	CreatedAt   *time.Time
}

type FoodDatabase struct {
	ID              uuid.UUID
	Name            string
	Brand           *string
	CaloriesPer100g *int
	ProteinPer100g  *float64
	CarbsPer100g    *float64
	FatPer100g      *float64
	Source          *string
	CreatedAt       *time.Time
	Barcode         *string
	Calories        *int
	Protein         *float64
	Carbs           *float64
	Fat             *float64
	ServingSize     *int
	ServingUnit     *string
	Verified        *bool
	UpdatedAt       *time.Time
}

type FoodItem struct {
	ID          uuid.UUID
	MealID      uuid.UUID
	Name        string
	PortionSize *float64
	PortionUnit *string
	Calories    int
	Protein     *float64
	Carbs       *float64
	Fat         *float64
	Source      *string
}

type Meal struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	MealType  *string
	MealDate  pgtype.Date
	MealTime  pgtype.Time
	PhotoUrl  *string
	CreatedAt *time.Time
}

type Subscription struct {
	ID                              int64
	UserID                          uuid.UUID
	RevenuecatUserID                string
	RevenuecatOriginalTransactionID *string
	IsActive                        bool
	Plan                            string
	IsTrial                         bool
	CurrentPeriodStart              pgtype.Timestamptz
	CurrentPeriodEnd                pgtype.Timestamptz
	LastEventID                     *string
	LastEventType                   *string
	LastEventAt                     pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

type User struct {
	ID                   uuid.UUID
	FirebaseUid          string
	Email                *string
	DisplayName          *string
	PhotoUrl             *string
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
	Weight               *int
	Height               *int
	Age                  *int
	Gender               *string
	ActivityLevel        *string
	Language             *string
	NotificationsEnabled *bool
	Timezone             *string
}

type UserAchievement struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	AchievementID uuid.UUID
	Unlocked      bool
	Progress      int
	UnlockedAt    *time.Time
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
}

type UserGoal struct {
	UserID        uuid.UUID
	DailyCalories int
	Protein       *int
	Carbs         *int
	Fat           *int
	UpdatedAt     *time.Time
}

type UserStat struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	CurrentStreak         int
	LongestStreak         int
	TotalMealsLogged      int
	TotalDaysLogged       int
	TotalCaloriesConsumed int
	TotalProteinConsumed  int
	TotalCarbsConsumed    int
	TotalFatConsumed      int
	LastLogDate           pgtype.Date
	CreatedAt             *time.Time
	UpdatedAt             *time.Time
}
