// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddNutritionToStats(ctx context.Context, arg AddNutritionToStatsParams) error
	CheckEventProcessed(ctx context.Context, lastEventID *string) (bool, error)
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	CreateFoodFromBarcode(ctx context.Context, arg CreateFoodFromBarcodeParams) (FoodDatabase, error)
	CreateFoodItem(ctx context.Context, arg CreateFoodItemParams) error
	CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error)
	CreateOrResetAIUsage(ctx context.Context, arg CreateOrResetAIUsageParams) (AiUsage, error)
	CreateStandaloneFoodItem(ctx context.Context, arg CreateStandaloneFoodItemParams) (FoodItem, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserStats(ctx context.Context, userID pgtype.UUID) (UserStat, error)
	DeleteFoodItem(ctx context.Context, id pgtype.UUID) error
	ExistsUserByFirebaseUID(ctx context.Context, firebaseUid string) (bool, error)
	GetAIUsage(ctx context.Context, arg GetAIUsageParams) (AiUsage, error)
	GetAIUsageByPeriod(ctx context.Context, arg GetAIUsageByPeriodParams) (AiUsage, error)
	GetAchievementByID(ctx context.Context, id pgtype.UUID) (Achievement, error)
	GetAchievementsByCategory(ctx context.Context, category string) ([]Achievement, error)
	GetAllAchievements(ctx context.Context) ([]Achievement, error)
	GetFeedback(ctx context.Context, id pgtype.UUID) (Feedback, error)
	GetFeedbackByType(ctx context.Context, arg GetFeedbackByTypeParams) ([]Feedback, error)
	GetFeedbackByUser(ctx context.Context, userID pgtype.UUID) ([]Feedback, error)
	GetFoodByBarcode(ctx context.Context, barcode *string) (FoodDatabase, error)
	GetFoodByID(ctx context.Context, id pgtype.UUID) (FoodDatabase, error)
	GetFoodItemByID(ctx context.Context, id pgtype.UUID) (FoodItem, error)
	GetFoodItemsByMealID(ctx context.Context, mealID pgtype.UUID) ([]FoodItem, error)
	GetFoodItemsByMealIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]FoodItem, error)
	GetMealByID(ctx context.Context, id pgtype.UUID) (Meal, error)
	GetMealsByUserAndDate(ctx context.Context, arg GetMealsByUserAndDateParams) ([]Meal, error)
	GetRecentFoods(ctx context.Context, arg GetRecentFoodsParams) ([]GetRecentFoodsRow, error)
	GetSubscriptionByRevenueCatUserID(ctx context.Context, revenuecatUserID string) (Subscription, error)
	GetSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (Subscription, error)
	GetUserAchievement(ctx context.Context, arg GetUserAchievementParams) (UserAchievement, error)
	GetUserAchievements(ctx context.Context, userID pgtype.UUID) ([]GetUserAchievementsRow, error)
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserGoalByUserID(ctx context.Context, userID pgtype.UUID) (UserGoal, error)
	GetUserStats(ctx context.Context, userID pgtype.UUID) (UserStat, error)
	GetUserUnlockedAchievements(ctx context.Context, userID pgtype.UUID) ([]GetUserUnlockedAchievementsRow, error)
	IncrementAIUsage(ctx context.Context, arg IncrementAIUsageParams) (AiUsage, error)
	IncrementMealCount(ctx context.Context, userID pgtype.UUID) error
	ListActiveSubscriptions(ctx context.Context) ([]Subscription, error)
	ListExpiredSubscriptions(ctx context.Context) ([]Subscription, error)
	ListFeedback(ctx context.Context, arg ListFeedbackParams) ([]Feedback, error)
	ListUserAIUsage(ctx context.Context, userID pgtype.UUID) ([]AiUsage, error)
	ListVerifiedFoods(ctx context.Context, arg ListVerifiedFoodsParams) ([]FoodDatabase, error)
	ResetAIUsage(ctx context.Context) error
	SearchFoodByName(ctx context.Context, arg SearchFoodByNameParams) ([]FoodDatabase, error)
	SearchFoodDatabase(ctx context.Context, arg SearchFoodDatabaseParams) ([]SearchFoodDatabaseRow, error)
	UpdateAchievementProgress(ctx context.Context, arg UpdateAchievementProgressParams) error
	UpdateFeedbackStatus(ctx context.Context, arg UpdateFeedbackStatusParams) error
	UpdateFoodItem(ctx context.Context, arg UpdateFoodItemParams) error
	UpdateFoodItemComplete(ctx context.Context, arg UpdateFoodItemCompleteParams) (FoodItem, error)
	UpdateFoodVerified(ctx context.Context, arg UpdateFoodVerifiedParams) error
	UpdateStreakAndLastLogDate(ctx context.Context, arg UpdateStreakAndLastLogDateParams) error
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserNotifications(ctx context.Context, arg UpdateUserNotificationsParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	UpsertUserAchievement(ctx context.Context, arg UpsertUserAchievementParams) error
	UpsertUserGoal(ctx context.Context, arg UpsertUserGoalParams) (UserGoal, error)
}

var _ Querier = (*Queries)(nil)
