// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats_range.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMealsWithFoodsInRange = `-- name: GetMealsWithFoodsInRange :many
SELECT 
    m.id as meal_id,
    m.user_id,
    m.meal_type,
    m.meal_date,
    m.meal_time,
    m.photo_url,
    m.created_at as meal_created_at,
    fi.id as food_id,
    fi.name as food_name,
    fi.portion_size,
    fi.portion_unit,
    fi.calories,
    fi.protein,
    fi.carbs,
    fi.fat,
    fi.source
FROM meals m
LEFT JOIN food_items fi ON fi.meal_id = m.id
WHERE m.user_id = $1 
  AND m.meal_date >= $2 
  AND m.meal_date <= $3
ORDER BY m.meal_date ASC, m.meal_time ASC, m.created_at ASC
`

type GetMealsWithFoodsInRangeParams struct {
	UserID     uuid.UUID
	MealDate   pgtype.Date
	MealDate_2 pgtype.Date
}

type GetMealsWithFoodsInRangeRow struct {
	MealID        uuid.UUID
	UserID        uuid.UUID
	MealType      *string
	MealDate      pgtype.Date
	MealTime      pgtype.Time
	PhotoUrl      *string
	MealCreatedAt *time.Time
	FoodID        uuid.UUID
	FoodName      *string
	PortionSize   *float64
	PortionUnit   *string
	Calories      *int
	Protein       *float64
	Carbs         *float64
	Fat           *float64
	Source        *string
}

func (q *Queries) GetMealsWithFoodsInRange(ctx context.Context, arg GetMealsWithFoodsInRangeParams) ([]GetMealsWithFoodsInRangeRow, error) {
	rows, err := q.db.Query(ctx, getMealsWithFoodsInRange, arg.UserID, arg.MealDate, arg.MealDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMealsWithFoodsInRangeRow{}
	for rows.Next() {
		var i GetMealsWithFoodsInRangeRow
		if err := rows.Scan(
			&i.MealID,
			&i.UserID,
			&i.MealType,
			&i.MealDate,
			&i.MealTime,
			&i.PhotoUrl,
			&i.MealCreatedAt,
			&i.FoodID,
			&i.FoodName,
			&i.PortionSize,
			&i.PortionUnit,
			&i.Calories,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
