// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkEventProcessed = `-- name: CheckEventProcessed :one
SELECT EXISTS(
    SELECT 1 FROM subscriptions
    WHERE last_event_id = $1
)
`

func (q *Queries) CheckEventProcessed(ctx context.Context, lastEventID *string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEventProcessed, lastEventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id,
    revenuecat_user_id,
    revenuecat_original_transaction_id,
    is_active,
    plan,
    is_trial,
    current_period_start,
    current_period_end,
    last_event_id,
    last_event_type,
    last_event_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, revenuecat_user_id, revenuecat_original_transaction_id, is_active, plan, is_trial, current_period_start, current_period_end, last_event_id, last_event_type, last_event_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID                          uuid.UUID
	RevenuecatUserID                string
	RevenuecatOriginalTransactionID *string
	IsActive                        bool
	Plan                            string
	IsTrial                         bool
	CurrentPeriodStart              pgtype.Timestamptz
	CurrentPeriodEnd                pgtype.Timestamptz
	LastEventID                     *string
	LastEventType                   *string
	LastEventAt                     pgtype.Timestamptz
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.RevenuecatUserID,
		arg.RevenuecatOriginalTransactionID,
		arg.IsActive,
		arg.Plan,
		arg.IsTrial,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.LastEventID,
		arg.LastEventType,
		arg.LastEventAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevenuecatUserID,
		&i.RevenuecatOriginalTransactionID,
		&i.IsActive,
		&i.Plan,
		&i.IsTrial,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.LastEventID,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByRevenueCatUserID = `-- name: GetSubscriptionByRevenueCatUserID :one
SELECT id, user_id, revenuecat_user_id, revenuecat_original_transaction_id, is_active, plan, is_trial, current_period_start, current_period_end, last_event_id, last_event_type, last_event_at, created_at, updated_at FROM subscriptions
WHERE revenuecat_user_id = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByRevenueCatUserID(ctx context.Context, revenuecatUserID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByRevenueCatUserID, revenuecatUserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevenuecatUserID,
		&i.RevenuecatOriginalTransactionID,
		&i.IsActive,
		&i.Plan,
		&i.IsTrial,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.LastEventID,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, revenuecat_user_id, revenuecat_original_transaction_id, is_active, plan, is_trial, current_period_start, current_period_end, last_event_id, last_event_type, last_event_at, created_at, updated_at FROM subscriptions
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevenuecatUserID,
		&i.RevenuecatOriginalTransactionID,
		&i.IsActive,
		&i.Plan,
		&i.IsTrial,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.LastEventID,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSubscriptions = `-- name: ListActiveSubscriptions :many
SELECT id, user_id, revenuecat_user_id, revenuecat_original_transaction_id, is_active, plan, is_trial, current_period_start, current_period_end, last_event_id, last_event_type, last_event_at, created_at, updated_at FROM subscriptions
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RevenuecatUserID,
			&i.RevenuecatOriginalTransactionID,
			&i.IsActive,
			&i.Plan,
			&i.IsTrial,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.LastEventID,
			&i.LastEventType,
			&i.LastEventAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSubscriptions = `-- name: ListExpiredSubscriptions :many
SELECT id, user_id, revenuecat_user_id, revenuecat_original_transaction_id, is_active, plan, is_trial, current_period_start, current_period_end, last_event_id, last_event_type, last_event_at, created_at, updated_at FROM subscriptions
WHERE is_active = true
AND current_period_end < NOW()
ORDER BY current_period_end ASC
`

func (q *Queries) ListExpiredSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listExpiredSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RevenuecatUserID,
			&i.RevenuecatOriginalTransactionID,
			&i.IsActive,
			&i.Plan,
			&i.IsTrial,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.LastEventID,
			&i.LastEventType,
			&i.LastEventAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
    is_active = $2,
    plan = $3,
    is_trial = $4,
    current_period_start = $5,
    current_period_end = $6,
    last_event_id = $7,
    last_event_type = $8,
    last_event_at = $9,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, revenuecat_user_id, revenuecat_original_transaction_id, is_active, plan, is_trial, current_period_start, current_period_end, last_event_id, last_event_type, last_event_at, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	UserID             uuid.UUID
	IsActive           bool
	Plan               string
	IsTrial            bool
	CurrentPeriodStart pgtype.Timestamptz
	CurrentPeriodEnd   pgtype.Timestamptz
	LastEventID        *string
	LastEventType      *string
	LastEventAt        pgtype.Timestamptz
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.UserID,
		arg.IsActive,
		arg.Plan,
		arg.IsTrial,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.LastEventID,
		arg.LastEventType,
		arg.LastEventAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevenuecatUserID,
		&i.RevenuecatOriginalTransactionID,
		&i.IsActive,
		&i.Plan,
		&i.IsTrial,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.LastEventID,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    user_id,
    revenuecat_user_id,
    revenuecat_original_transaction_id,
    is_active,
    plan,
    is_trial,
    current_period_start,
    current_period_end,
    last_event_id,
    last_event_type,
    last_event_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (user_id) DO UPDATE SET
    is_active = EXCLUDED.is_active,
    plan = EXCLUDED.plan,
    is_trial = EXCLUDED.is_trial,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    last_event_id = EXCLUDED.last_event_id,
    last_event_type = EXCLUDED.last_event_type,
    last_event_at = EXCLUDED.last_event_at,
    revenuecat_original_transaction_id = EXCLUDED.revenuecat_original_transaction_id,
    updated_at = NOW()
RETURNING id, user_id, revenuecat_user_id, revenuecat_original_transaction_id, is_active, plan, is_trial, current_period_start, current_period_end, last_event_id, last_event_type, last_event_at, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	UserID                          uuid.UUID
	RevenuecatUserID                string
	RevenuecatOriginalTransactionID *string
	IsActive                        bool
	Plan                            string
	IsTrial                         bool
	CurrentPeriodStart              pgtype.Timestamptz
	CurrentPeriodEnd                pgtype.Timestamptz
	LastEventID                     *string
	LastEventType                   *string
	LastEventAt                     pgtype.Timestamptz
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.UserID,
		arg.RevenuecatUserID,
		arg.RevenuecatOriginalTransactionID,
		arg.IsActive,
		arg.Plan,
		arg.IsTrial,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.LastEventID,
		arg.LastEventType,
		arg.LastEventAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevenuecatUserID,
		&i.RevenuecatOriginalTransactionID,
		&i.IsActive,
		&i.Plan,
		&i.IsTrial,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.LastEventID,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
