// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, firebase_uid, email, display_name, photo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, firebase_uid, email, display_name, photo_url, created_at, updated_at
`

type CreateUserParams struct {
	ID          pgtype.UUID
	FirebaseUid string
	Email       *string
	DisplayName *string
	PhotoUrl    *string
}

type CreateUserRow struct {
	ID          pgtype.UUID
	FirebaseUid string
	Email       *string
	DisplayName *string
	PhotoUrl    *string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirebaseUid,
		arg.Email,
		arg.DisplayName,
		arg.PhotoUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsUserByFirebaseUID = `-- name: ExistsUserByFirebaseUID :one
SELECT EXISTS(SELECT 1 FROM users WHERE firebase_uid = $1)
`

func (q *Queries) ExistsUserByFirebaseUID(ctx context.Context, firebaseUid string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByFirebaseUID, firebaseUid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, photo_url, created_at, updated_at,
       weight, height, age, gender, activity_level, language, notifications_enabled
FROM users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.Height,
		&i.Age,
		&i.Gender,
		&i.ActivityLevel,
		&i.Language,
		&i.NotificationsEnabled,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, email, display_name, photo_url, created_at, updated_at,
       weight, height, age, gender, activity_level, language, notifications_enabled
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.Height,
		&i.Age,
		&i.Gender,
		&i.ActivityLevel,
		&i.Language,
		&i.NotificationsEnabled,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, display_name = $3, photo_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, email, display_name, photo_url, created_at, updated_at,
          weight, height, age, gender, activity_level, language, notifications_enabled
`

type UpdateUserParams struct {
	ID          pgtype.UUID
	Email       *string
	DisplayName *string
	PhotoUrl    *string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.Height,
		&i.Age,
		&i.Gender,
		&i.ActivityLevel,
		&i.Language,
		&i.NotificationsEnabled,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET photo_url = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID       pgtype.UUID
	PhotoUrl *string
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.PhotoUrl)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users
SET display_name = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          pgtype.UUID
	DisplayName *string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateUserNotifications = `-- name: UpdateUserNotifications :exec
UPDATE users
SET notifications_enabled = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserNotificationsParams struct {
	ID                   pgtype.UUID
	NotificationsEnabled *bool
}

func (q *Queries) UpdateUserNotifications(ctx context.Context, arg UpdateUserNotificationsParams) error {
	_, err := q.db.Exec(ctx, updateUserNotifications, arg.ID, arg.NotificationsEnabled)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET
    display_name = $2,
    email = $3,
    photo_url = $4,
    weight = $5,
    height = $6,
    age = $7,
    gender = $8,
    activity_level = $9,
    language = $10,
    notifications_enabled = $11,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID                   pgtype.UUID
	DisplayName          *string
	Email                *string
	PhotoUrl             *string
	Weight               *int
	Height               *int
	Age                  *int
	Gender               *string
	ActivityLevel        *string
	Language             *string
	NotificationsEnabled *bool
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.PhotoUrl,
		arg.Weight,
		arg.Height,
		arg.Age,
		arg.Gender,
		arg.ActivityLevel,
		arg.Language,
		arg.NotificationsEnabled,
	)
	return err
}
