// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNutritionToStats = `-- name: AddNutritionToStats :exec
UPDATE user_stats SET
    total_calories_consumed = total_calories_consumed + $2,
    total_protein_consumed = total_protein_consumed + $3,
    total_carbs_consumed = total_carbs_consumed + $4,
    total_fat_consumed = total_fat_consumed + $5,
    updated_at = NOW()
WHERE user_id = $1
`

type AddNutritionToStatsParams struct {
	UserID                pgtype.UUID
	TotalCaloriesConsumed int
	TotalProteinConsumed  int
	TotalCarbsConsumed    int
	TotalFatConsumed      int
}

func (q *Queries) AddNutritionToStats(ctx context.Context, arg AddNutritionToStatsParams) error {
	_, err := q.db.Exec(ctx, addNutritionToStats,
		arg.UserID,
		arg.TotalCaloriesConsumed,
		arg.TotalProteinConsumed,
		arg.TotalCarbsConsumed,
		arg.TotalFatConsumed,
	)
	return err
}

const createUserStats = `-- name: CreateUserStats :one
INSERT INTO user_stats (user_id)
VALUES ($1)
RETURNING id, user_id, current_streak, longest_streak, total_meals_logged, total_days_logged, total_calories_consumed, total_protein_consumed, total_carbs_consumed, total_fat_consumed, last_log_date, created_at, updated_at
`

func (q *Queries) CreateUserStats(ctx context.Context, userID pgtype.UUID) (UserStat, error) {
	row := q.db.QueryRow(ctx, createUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.TotalMealsLogged,
		&i.TotalDaysLogged,
		&i.TotalCaloriesConsumed,
		&i.TotalProteinConsumed,
		&i.TotalCarbsConsumed,
		&i.TotalFatConsumed,
		&i.LastLogDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT id, user_id, current_streak, longest_streak, total_meals_logged, total_days_logged, total_calories_consumed, total_protein_consumed, total_carbs_consumed, total_fat_consumed, last_log_date, created_at, updated_at FROM user_stats WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID pgtype.UUID) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.TotalMealsLogged,
		&i.TotalDaysLogged,
		&i.TotalCaloriesConsumed,
		&i.TotalProteinConsumed,
		&i.TotalCarbsConsumed,
		&i.TotalFatConsumed,
		&i.LastLogDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementMealCount = `-- name: IncrementMealCount :exec
UPDATE user_stats SET
    total_meals_logged = total_meals_logged + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementMealCount(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementMealCount, userID)
	return err
}

const updateStreakAndLastLogDate = `-- name: UpdateStreakAndLastLogDate :exec
UPDATE user_stats SET
    current_streak = $2,
    longest_streak = GREATEST(longest_streak, $2),
    last_log_date = $3,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateStreakAndLastLogDateParams struct {
	UserID        pgtype.UUID
	CurrentStreak int
	LastLogDate   pgtype.Date
}

func (q *Queries) UpdateStreakAndLastLogDate(ctx context.Context, arg UpdateStreakAndLastLogDateParams) error {
	_, err := q.db.Exec(ctx, updateStreakAndLastLogDate, arg.UserID, arg.CurrentStreak, arg.LastLogDate)
	return err
}

const updateUserStats = `-- name: UpdateUserStats :exec
UPDATE user_stats SET
    current_streak = $2,
    longest_streak = $3,
    total_meals_logged = $4,
    total_days_logged = $5,
    total_calories_consumed = $6,
    total_protein_consumed = $7,
    total_carbs_consumed = $8,
    total_fat_consumed = $9,
    last_log_date = $10,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserStatsParams struct {
	UserID                pgtype.UUID
	CurrentStreak         int
	LongestStreak         int
	TotalMealsLogged      int
	TotalDaysLogged       int
	TotalCaloriesConsumed int
	TotalProteinConsumed  int
	TotalCarbsConsumed    int
	TotalFatConsumed      int
	LastLogDate           pgtype.Date
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error {
	_, err := q.db.Exec(ctx, updateUserStats,
		arg.UserID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.TotalMealsLogged,
		arg.TotalDaysLogged,
		arg.TotalCaloriesConsumed,
		arg.TotalProteinConsumed,
		arg.TotalCarbsConsumed,
		arg.TotalFatConsumed,
		arg.LastLogDate,
	)
	return err
}
