// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, firebase_uid, email, display_name, photo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, firebase_uid, email, display_name, photo_url, created_at, updated_at
`

type CreateUserParams struct {
	ID          uuid.UUID
	FirebaseUid string
	Email       *string
	DisplayName *string
	PhotoUrl    *string
}

type CreateUserRow struct {
	ID          uuid.UUID
	FirebaseUid string
	Email       *string
	DisplayName *string
	PhotoUrl    *string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirebaseUid,
		arg.Email,
		arg.DisplayName,
		arg.PhotoUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsUserByFirebaseUID = `-- name: ExistsUserByFirebaseUID :one
SELECT EXISTS(SELECT 1 FROM users WHERE firebase_uid = $1)
`

func (q *Queries) ExistsUserByFirebaseUID(ctx context.Context, firebaseUid string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByFirebaseUID, firebaseUid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, photo_url, created_at, updated_at,
       weight, height, age, gender, activity_level, language, notifications_enabled, timezone,
       daily_reminder_enabled, daily_reminder_time, streak_risk_enabled, achievement_unlocked_enabled
FROM users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.Height,
		&i.Age,
		&i.Gender,
		&i.ActivityLevel,
		&i.Language,
		&i.NotificationsEnabled,
		&i.Timezone,
		&i.DailyReminderEnabled,
		&i.DailyReminderTime,
		&i.StreakRiskEnabled,
		&i.AchievementUnlockedEnabled,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, email, display_name, photo_url, created_at, updated_at,
       weight, height, age, gender, activity_level, language, notifications_enabled, timezone,
       daily_reminder_enabled, daily_reminder_time, streak_risk_enabled, achievement_unlocked_enabled
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.Height,
		&i.Age,
		&i.Gender,
		&i.ActivityLevel,
		&i.Language,
		&i.NotificationsEnabled,
		&i.Timezone,
		&i.DailyReminderEnabled,
		&i.DailyReminderTime,
		&i.StreakRiskEnabled,
		&i.AchievementUnlockedEnabled,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, display_name = $3, photo_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, email, display_name, photo_url, created_at, updated_at,
          weight, height, age, gender, activity_level, language, notifications_enabled, timezone,
          daily_reminder_enabled, daily_reminder_time, streak_risk_enabled, achievement_unlocked_enabled
`

type UpdateUserParams struct {
	ID          uuid.UUID
	Email       *string
	DisplayName *string
	PhotoUrl    *string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.Height,
		&i.Age,
		&i.Gender,
		&i.ActivityLevel,
		&i.Language,
		&i.NotificationsEnabled,
		&i.Timezone,
		&i.DailyReminderEnabled,
		&i.DailyReminderTime,
		&i.StreakRiskEnabled,
		&i.AchievementUnlockedEnabled,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET photo_url = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID       uuid.UUID
	PhotoUrl *string
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.PhotoUrl)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users
SET display_name = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName *string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateUserNotificationPreferences = `-- name: UpdateUserNotificationPreferences :exec
UPDATE users
SET
    notifications_enabled = COALESCE($1, notifications_enabled),
    daily_reminder_enabled = COALESCE($2, daily_reminder_enabled),
    daily_reminder_time = COALESCE($3, daily_reminder_time),
    streak_risk_enabled = COALESCE($4, streak_risk_enabled),
    achievement_unlocked_enabled = COALESCE($5, achievement_unlocked_enabled),
    updated_at = NOW()
WHERE id = $6
`

type UpdateUserNotificationPreferencesParams struct {
	NotificationsEnabled       *bool
	DailyReminderEnabled       *bool
	DailyReminderTime          *string
	StreakRiskEnabled          *bool
	AchievementUnlockedEnabled *bool
	ID                         uuid.UUID
}

func (q *Queries) UpdateUserNotificationPreferences(ctx context.Context, arg UpdateUserNotificationPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserNotificationPreferences,
		arg.NotificationsEnabled,
		arg.DailyReminderEnabled,
		arg.DailyReminderTime,
		arg.StreakRiskEnabled,
		arg.AchievementUnlockedEnabled,
		arg.ID,
	)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET
    display_name = $1,
    email = $2,
    photo_url = $3,
    weight = $4,
    height = $5,
    age = $6,
    gender = $7,
    activity_level = $8,
    language = $9,
    notifications_enabled = $10,
    timezone = $11,
    updated_at = NOW()
WHERE id = $12
`

type UpdateUserProfileParams struct {
	DisplayName          *string
	Email                *string
	PhotoUrl             *string
	Weight               *int
	Height               *int
	Age                  *int
	Gender               *string
	ActivityLevel        *string
	Language             *string
	NotificationsEnabled *bool
	Timezone             *string
	ID                   uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Email,
		arg.PhotoUrl,
		arg.Weight,
		arg.Height,
		arg.Age,
		arg.Gender,
		arg.ActivityLevel,
		arg.Language,
		arg.NotificationsEnabled,
		arg.Timezone,
		arg.ID,
	)
	return err
}
